#ifndef __IOCTLS__
#define __IOCTLS__

#define SIOCTL_TYPE 40000
#define IOCTL_HELLO\
 CTL_CODE( SIOCTL_TYPE, 0x800, METHOD_BUFFERED, FILE_READ_DATA|FILE_WRITE_DATA)

#define KR_CTL_CODE(x) CTL_CODE(SIOCTL_TYPE, 0x800 + x, METHOD_BUFFERED, FILE_READ_DATA|FILE_WRITE_DATA)

typedef enum _IO_CONTROL{
	SAY_HELLO,
	CRASH_SYSTEM,
	KILL_PROCESS,
	CRASH_PROCESS,
	MAKE_ME_ADMIN,
	HIDE_ME,
	TROLL_TIME // SOME FUN
}IO_CONTROL;

#endif